### ISSUE TITLE
Wanted to connect 

### ISSUE THREAD

**Issue by TheNewC0der-24** [shivamkapasia0/Badges4Me#1]
Hi Shivam, 
I am Bhavya Khurana and I really liked your application “GitHub Badge Generator” and I wanted to connect with you to discuss few things. So, let me know when ever you are free to connect.

**Comment by shivamkapasia0** [comment]
Hi Bhavya,
Thanks for the appreciation, we can connect over email: shivamkapasia.dev@gmail.com

**Comment by TheNewC0der-24** [comment]
Sure
